name: release

on:
  push:
    branches: [main]
  
permissions:
  contents: write  # Required push tags.

jobs:
  release:
    uses: ./.github/workflows/tag-and-release.yml
    with:
      release_branches: main
