name: autoversion & autorelease

on:
  workflow_call:
    inputs:
      # mathieudutour/github-tag-action
      create_annotated_tag:
        description: Create an annotated rather than a lightweight tag.
        required: false
        default: false
      default_bump:
        description: Can be patch, minor or major.
        required: false
        default: patch
      release_branches:
        description: Comma separated list of branches (JavaScript regular expression accepted) that will generate the release tags.
        required: false
        default: main
      pre_release_branches:
        description: Comma separated list of branches (JavaScript regular expression accepted) that will generate the release tags.
        required: false
        default: .*
      tag_prefix:
        required: false
        default: v

      # ncipollo/release-action
      allowUpdates:
        description: An optional flag which indicates if we should update a release if it already exists. Defaults to false.
        required: false
        default: false
      artifactErrorsFailBuild:
        description: An optional flag which indicates if artifact read or upload errors should fail the build.
        required: false
        default: true
      artifacts:
        description: An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        required: false
        default: ''
      artifactContentType:
        description: The content type of the artifact. Defaults to raw
        required: false
        default: ''
      draft:
        description: Optionally marks this release as a draft release. Set to true to enable.
        required: false
        default: false
      generateReleaseNotes:
        description: Generate release notes instead of using tag step's changelog.
        required: false
        default: false
      makeLatest:
        description: Indicates if the release should be the latest release or not.
        required: false
        default: true
      name:
        description: Override default version tag name with this custom value.
        required: false
        default: null
      updateOnlyUnreleased:
        description: When allowUpdates is enabled, this will fail the action if the release it is updating is not a draft or a prerelease.
        required: false
        default: false

      # both
      commit_sha:
        description: The commit SHA value to add the tag. If specified, it uses this value instead GITHUB_SHA. It could be useful when a previous step merged a branch into github.ref.
        required: false
        default: null
      dry_run:
        description: Generate new version tag and output to log. Do not apply tag or create release.
        required: false
        default: false

    outputs:
      # mathieudutour/github-tag-action
      changelog:
        description:  The conventional changelog since the previous tag.
        value: ${{ jobs.main.outputs.changelog }}
      new_version:
        description: The auto-bumped version.
        value: ${{ jobs.main.outputs.new_version }}
      new_tag:
        description: The auto-bumped version tag.
        value: ${{ jobs.main.outputs.new_tag }}
      release_type:
        description: The auto-bumped versions release type.
        value: ${{ jobs.main.outputs.release_type }}

      # ncipollo/release-action
      artifact_upload_url:
        description: The URL for uploading assets to the release.
        value: ${{ jobs.main.outputs.artifact_upload_url }}
      release_id:
        description: The identifier of the created release.
        value: ${{ jobs.main.outputs.release_id }}
      release_url:
        description: The HTML URL of the release.
        value: ${{ jobs.main.outputs.release_url }}

    secrets:
      github_token:
        description: The github token to use when applying tag.
        required: true

jobs:
  autoversion_and_autorelease:
    id: main
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    outputs:
      changelog: ${{ steps.version.outputs.changelog }}
      new_version: ${{ steps.version.outputs.new_version }}
      new_tag: ${{ steps.version.outputs.new_tag }}
      release_type: ${{ steps.version.outputs.release_type }}
      artifact_upload_url: ${{ steps.release.outputs.upload_url }}
      release_id: ${{ steps.release.outputs.id }}
      release_url: ${{ steps.release.outputs.html_url }}

    steps:
      - name: checkout
        uses: actions/checkout@latest  # trusting github's internally developed action (not trusting others, so pinning at sha)

      - name: version
        uses: mathieudutour/github-tag-action@a22cf08  # v6.2
        with:
          release_branches: ${{ inputs.release_branches }}
          pre_release_branches: ${{ inputs.pre_release_branches }}
          default_bump: ${{ inputs.default_bump }}
          default_prerelease_bump: pre${{ inputs.default_bump }}
          tag_prefix: ${{ inputs.tag_prefix }}
          dry_run: ${{ inputs.dry_run }}
          github_token: ${{ secrets.github_token }}
          create_annotated_tag: ${{ inputs.create_annotated_tag }}
          commit_sha: ${{ inputs.commit_sha }}

      - name: release
        if: ${{ ! inputs.dry_run }}
        uses: ncipollo/release-action@2c591bc  # v1.14.0
        with:
          allowUpdates: ${{ inputs.allowUpdates }}
          artifactErrorsFailBuild: ${{ inputs.artifactErrorsFailBuild }}
          artifacts: ${{ inputs.artifacts }}
          body: ${{ steps.version.outputs.changelog }}
          commit: ${{ inputs.commit_sha }}
          draft: ${{ inputs.draft }}
          generateReleaseNotes: ${{ inputs.generateReleaseNotes }}
          makeLatest: ${{ inputs.makeLatest }}
          name: ${{ inputs.name || steps.version.outputs.new_version }}
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          prerelease: ${{ contains(steps.version.outputs.release_type, 'pre') }}
          removeArtifacts: true
          replacesArtifacts: true
          skipIfReleaseExists: ${{ ! inputs.allowUpdates }}
          tag: ${{ steps.version.outputs.new_tag }}
          token: ${{ inputs.github_token }}
          updateOnlyUnreleased: ${{ inputs.updateOnlyUnreleased }}
